name: Build React + Vite

# Definir os gatilhos para o workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Configuração dos jobs do workflow
jobs:
  build:
    runs-on: ubuntu-latest #executa maquina Ubuntu

    steps:
      # 1. Checar o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. Configurar o node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  
    
    # 3. instalar dependencias 
      - name: Instalar dependências
        run: npm install

    # 4. Rodar os testes (opcional)

    # 5. Criar os artefatos ou build
      - name: Rodar build
        run: npm run build

      
      - name: Validar build
        run: ls -la dist

  deploy: 
    runs-on: ubuntu-latest
    steps:
    # 1. Fazer o deploy para o servidor via ssh
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.2.0  # Action para SSH
      with:
        host: ${{ secrets.HOST }}  # Defina isso no repositório em Secrets
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Defina a chave SSH no Secrets
        port: 22
        script: |
          sudo set enforce 0
          cd ./calculadora || git clone https://github.com/pedroivoadv/Projeto-DevOps-PUC-RS.git
          cd Projeto-DevOps-PUC-RS
          git pull origin main  # Ou outro comando para atualizar o código
          npm install
          pm2 start server.js  # Exemplo para reiniciar a aplicação Node.js com PM2    